import json
import os

translations = {
    "// 통합 메시지 & 파싱 타입": "// Unified Message & Parsing Types",
    "// 행성 & 태양계 시각화 타입": "// Planet & Solar System Visualization Types",
    "// 시각 매핑": "// Visual Mapping",
    "// 데이터": "// Data",
    "// 카테고리 계층 트리 타입": "// Category Hierarchy Tree Type",
    "// API 응답 타입": "// API Response Type",
    "// 앱 상태 타입": "// App State Type",
    "// 업로드 완료 → 분석 페이지로 이동": "// Upload complete -> Navigate to analysis page",
    "// 샘플 데이터 → 바로 태양계로": "// Sample data -> Go directly to solar system",
    "{/* 별 배경 */}": "{/* Star Background */}",
    "{/* 메인 콘텐츠 */}": "{/* Main Content */}",
    "{/* 항성 아이콘 */}": "{/* Star Icon */}",
    "{/* 이름 입력란 */}": "{/* Name Input Field */}",
    "{/* 내보내기 안내 토글 */}": "{/* Export Guide Toggle */}",
    "{/* 업로드 모달 */}": "{/* Upload Modal */}",
    "// ─── 유틸 ───": "// ─── Utilities ───",
    "// ─── 페이지 ───": "// ─── Page ───",
    "// 슬라이더 변경 시 planetCount만 업데이트.": "// Update only planetCount when slider changes.",
    "// 실제 행성 전환(exit/enter 애니메이션)은 SolarSystem → useTransitionPlanets가 전담.": "// Actual planet transition (exit/enter animation) is handled by SolarSystem -> useTransitionPlanets.",
    "// ── 샘플 데이터 로드 ──": "// ── Load Sample Data ──",
    "// ── 프로그레시브 분석 ──": "// ── Progressive Analysis ──",
    "// 유저 질문 추출": "// Extract user questions",
    "// Phase 1: Quick Analysis (250개 샘플)": "// Phase 1: Quick Analysis (250 samples)",
    "// 즉시 태양계 렌더링": "// Immediate solar system rendering",
    "// 질문이 150개 이하면 추가 분석 불필요": "// If there are 150 questions or less, no further analysis is needed",
    "// Phase 2: Background Refinement (전체 청크)": "// Phase 2: Background Refinement (all chunks)",
    "// rate limit 안전 간격 (첫 청크 전에도 대기 — Phase 1과의 간격)": "// Rate limit safety interval (wait before the first chunk too — interval with Phase 1)",
    "// 개별 청크 실패 시 무시하고 계속 진행": "// Ignore individual chunk failures and continue",
    "// 청크 결과가 없으면 Quick 결과 유지": "// Keep Quick result if there are no chunk results",
    "await sleep(15000); // merge 호출 전 rate limit 대기": "await sleep(15000); // Wait for rate limit before calling merge",
    "// ── 에러 ──": "// ── Error ──",
    "// ── 로딩 ──": "// ── Loading ──",
    "// ── 태양계 뷰 ──": "// ── Solar System View ──",
    "{/* ── 3D 캔버스 (항상 전체 화면, 패널 영향 없음) ── */}": "{/* ── 3D Canvas (always full screen, unaffected by panels) ── */}",
    "{/* 왼쪽 패널 토글 버튼 */}": "{/* Left Panel Toggle Button */}",
    "title={leftOpen ? '패널 닫기' : '패널 열기'}": "title={leftOpen ? 'Close Panel' : 'Open Panel'}",
    "{/* 프로그레시브 분석 뱃지 — 우측 상단 */}": "{/* Progressive Analysis Badge — Top Right */}",
    "{/* 행성 수 슬라이더 — 하단 중앙 */}": "{/* Planet Count Slider — Bottom Center */}",
    "{/* ── 왼쪽 패널 (절대 오버레이, 캔버스 크기 무영향) ── */}": "{/* ── Left Panel (absolute overlay, unaffected by canvas size) ── */}",
    "{/* ── 오른쪽 패널 (절대 오버레이, 캔버스 크기 무영향) ── */}": "{/* ── Right Panel (absolute overlay, unaffected by canvas size) ── */}",
    "// ChatGPT export: ZIP 안에 conversations.json": "// ChatGPT export: conversations.json inside ZIP",
    "// 다른 JSON 파일 찾기": "// Find other JSON files",
    "// 파일 크기 제한: 50MB": "// File size limit: 50MB",
    "// 파싱 결과 검증": "// Verify parsing result",
    "// ─── 헬퍼 ───": "// ─── Helpers ───",
    "// ─── 샘플 CategoryNode 트리 ───": "// ─── Sample CategoryNode Tree ───",
    "// 총 300개 질문, 6개 depth-0, 17개 depth-1": "// Total 300 questions, 6 depth-0, 17 depth-1",
    "// recentActivityScore: Programming/Mathematics는 최근 30일 집중 → 높은 점수": "// recentActivityScore: Programming/Mathematics concentrated in the last 30 days -> high score",
    "// → emissiveIntensity(발광)에 반영되어 \"가장 뜨거운 행성\" 효과": "// -> reflected in emissiveIntensity to create \"hottest planet\" effect",
    "// planets를 tree에서 동적 생성 → tree와 항상 일관성 보장": "// Dynamically create planets from tree -> ensures consistency with tree",
    "// ─── 유틸: 배열에서 고르게 N개 샘플링 ───": "// ─── Utility: evenly sample N items from array ───",
    "// 질문을 maxLen자로 잘라 토큰 절약 (분류에는 앞부분만 충분)": "// Trim questions to maxLen characters to save tokens (start is enough for classification)",
    "// ─── LLM 호출 (재시도 최대 2회) ───": "// ─── LLM Call (max 2 retries) ───",
    "// mode=quick  : messages에서 250개 샘플 → 즉시 응답 (초기 태양계)": "// mode=quick: 250 samples from messages -> immediate response (initial solar system)",
    "// mode=chunk  : questions 배열을 분류 → chunkTree 반환": "// mode=chunk: classify questions array -> return chunkTree",
    "// mode=merge  : chunkTrees 배열을 병합 → 최종 tree + planets 반환": "// mode=merge: merge chunkTrees array -> return final tree + planets",
    "// ── mode=chunk: 청크 하나 분류 ──": "// ── mode=chunk: classify one chunk ──",
    "// ── mode=merge: 청크 트리들 병합 ──": "// ── mode=merge: merge chunk trees ──",
    "// ── mode=quick (기본): 250개 샘플 → 즉시 태양계 ──": "// ── mode=quick (default): 250 samples -> immediate solar system ──",
    "// Step 9에서 구현 예정: html2canvas + Supabase Storage": "// To be implemented in Step 9: html2canvas + Supabase Storage",
    "// SCENE_CONFIG — 보충 문서 Section 8 기준 정밀 파라미터": "// SCENE_CONFIG — Precise parameters based on Supplementary Document Section 8",
    "// ═══ 배경 ═══": "// ═══ Background ═══",
    "// ═══ 안개 ═══": "// ═══ Fog ═══",
    "// ═══ 항성 ═══": "// ═══ Star ═══",
    "// ═══ 궤도 ═══": "// ═══ Orbit ═══",
    "// ═══ 그리드 ═══": "// ═══ Grid ═══",
    "// ═══ 후처리 ═══": "// ═══ Post Processing ═══",
    "// ═══ 카메라 ═══": "// ═══ Camera ═══",
    "// ═══ 행성 색상 팔레트 ═══": "// ═══ Planet Color Palette ═══",
    "// ═══ 애니메이션 ═══": "// ═══ Animation ═══",
    "// ═══ 성능 ═══": "// ═══ Performance ═══",
    "{/* 중앙 항성 애니메이션 */}": "{/* Central Star Animation */}",
    "{/* 질문 수 */}": "{/* Question Count */}",
    "{/* 스텝 목록 */}": "{/* Step List */}",
    "{/* 아이콘 */}": "{/* Icon */}",
    "{/* 라벨 */}": "{/* Label */}",
    "{/* 닫기 버튼 */}": "{/* Close Button */}",
    "{/* 행성 헤더 */}": "{/* Planet Header */}",
    "{/* 성장 추세 */}": "{/* Growth Trend */}",
    "{/* 설명 */}": "{/* Description */}",
    "{/* 대표 질문 */}": "{/* Representative Questions */}",
    "{/* 위성 (세부 토픽) */}": "{/* Moons (Sub-Topics) */}",
    "{/* 활동 점수 바 */}": "{/* Activity Score Bar */}",
    "{/* 헤더 */}": "{/* Header */}",
    "{/* 분포 차트 */}": "{/* Distribution Chart */}",
    "{/* 활동 타임라인 */}": "{/* Activity Timeline */}",
    "{/* 행성 목록 */}": "{/* Planet List */}",
    "{/* 드래그 존 */}": "{/* Drag Zone */}",
    "{/* 에러 */}": "{/* Error */}",
    "{/* 파싱 미리보기 */}": "{/* Parsing Preview */}",
    "{/* 플랫폼 배지 */}": "{/* Platform Badge */}",
    "{/* 통계 카드 */}": "{/* Stat Card */}",
    "{/* 날짜 범위 */}": "{/* Date Range */}",
    "{/* 버튼 */}": "{/* Button */}",
    "{/* 플랫폼 export 안내 */}": "{/* Platform Export Guide */}",
    "// \"완료\" 3초 후 자동 페이드아웃": "// Auto fadeout 3 seconds after \"Complete\"",
    "{/* 스피너 */}": "{/* Spinner */}",
    "{/* 프로그레스 바 */}": "{/* Progress Bar */}",
    "// recentActivityScore를 기반으로 가상의 7일 활동 데이터 생성": "// Create virtual 7-day activity data based on recentActivityScore",
    "// 최근일수록 recentActivityScore 높은 행성의 가중치를 높임": "// Increase the weight of planets with high recentActivityScore",
    "selected?: boolean; // 클릭(포커스)된 행성인지": "selected?: boolean; // Whether the planet is clicked (focused)",
    "// 궤도 파라미터 — 결정적 생성 (리렌더 시 동일)": "// Orbit parameters — deterministic generation (identical on re-render)",
    "// 카메라 거리 기반 LOD": "// Camera distance-based LOD",
    "// 타원 궤도 위 위치 계산": "// Calculate position on elliptical orbit",
    "// LOD용 카메라 거리 (60프레임마다 갱신으로 최적화)": "// Camera distance for LOD (optimized by updating every 60 frames)",
    "// 글로우 맥동": "// Glow pulsation",
    "{/* 타원 궤도선 */}": "{/* Elliptical Orbit Line */}",
    "{/* 행성 그룹 (useFrame으로 위치 업데이트) */}": "{/* Planet Group (position updated entirely with useFrame) */}",
    "{/* 행성 본체 */}": "{/* Planet Body */}",
    "{/* 글로우 레이어 */}": "{/* Glow Layer */}",
    "{/* 행성 이름 라벨 — drei Text (DOM 없이 3D 텍스트) */}": "{/* Planet Name Label — drei Text (3D text without DOM) */}",
    "{/* 위성들 */}": "{/* Moons */}",
    "// 전환 타입": "// Transition type",
    "// scale 스프링: appear 0→1, disappear 1→0": "// Scale spring: appear 0->1, disappear 1->0",
    "delay: entering ? 400 : 0,           // 보충 문서 타이밍: appear는 400ms 딜레이": "delay: entering ? 400 : 0,           // Supp doc timing: 400ms delay for appear",
    "} catch { /* 무시 */ }": "} catch { /* ignore */ }",
    "// planetCount 변경 시 전환 실행": "// Execute transition when planetCount changes",
    "{/* 전환 애니메이션이 적용된 행성들 */}": "{/* Planets with transition animations */}",
    "semiMajorAxis: number;   // 장축 반지름 (a)": "semiMajorAxis: number;   // Semi-major axis radius (a)",
    "eccentricity?: number;   // 이심률 0=원, 0.3=약한 타원": "eccentricity?: number;   // Eccentricity 0=circle, 0.3=weak ellipse",
    "inclination?: number;    // X축 기울기 (라디안)": "inclination?: number;    // X-axis inclination (radians)",
    "rotation?: number;       // Y축 회전 (레이어링)": "rotation?: number;       // Y-axis rotation (layering)",
    "// 단축 b = a * sqrt(1 - e²)": "// Minor axis b = a * sqrt(1 - e²)",
    "// 기울기 (X축 기준 회전)": "// Inclination (rotation around X-axis)",
    "// 타원 궤도 위 행성 위치 계산 (useFrame 안에서 호출)": "// Calculate planet position on elliptical orbit (called inside useFrame)",
    "// Y축 회전 적용": "// Apply Y-axis rotation",
    "// 문자열 → 결정적 0~1 해시 (DJB2 변형)": "// String -> deterministic 0~1 hash (DJB2 variant)",
    "// 행성 ID로부터 궤도 파라미터 결정적 생성": "// Deterministic generation of orbit parameters from planet ID",
    "// (planet count 변경에도 안정적)": "// (Stable even with planet count changes)",
    "// forwardRef로 부모(SolarSystem)가 포커스 메서드를 호출할 수 있게 함": "// Allows parent (SolarSystem) to call the focus method via forwardRef",
    "// 트랜지션 중 OrbitControls 비활성화": "// Disable OrbitControls during transition",
    "// 부모로 메서드 노출": "// Expose methods to parent",
    "{/* 투명 배경 평면 — 클릭 시 뷰 리셋 */}": "{/* Transparent background plane — reset view on click */}",
    "showLabel?: boolean; // 행성 클릭(선택) 시에만 true": "showLabel?: boolean; // True only when the planet is clicked (selected)",
    "// useFrame이 필요한 컴포넌트는 Canvas 내부에서 사용해야 함": "// Components requiring useFrame must be used inside Canvas",
    "// 프로덕션용 — 고정 파라미터": "// Production — fixed parameters",
    "// 개발용 — leva GUI로 실시간 파라미터 조절": "// Development — real-time parameter control with leva GUI",
    "// leva는 클라이언트 사이드에서만 동작하므로 dynamic import 패턴": "// leva only works on the client-side, dynamic import pattern",
    "// 여기서는 직접 사용 (이미 'use client')": "// Using directly here (already 'use client')",
    "// 익스포트 — dev/prod 자동 분기": "// Export — auto branch for dev/prod",
    "// 셰이더 머티리얼 정의": "// Shader material definition",
    "uColor1: new THREE.Color('#ffffff'),  // 중심 (밝은 흰색)": "uColor1: new THREE.Color('#ffffff'),  // Center (bright white)",
    "uColor2: new THREE.Color('#4FC3F7'),  // 중간 (시안)": "uColor2: new THREE.Color('#4FC3F7'),  // Middle (cyan)",
    "uColor3: new THREE.Color('#0288D1'),  // 외곽 (진한 파랑)": "uColor3: new THREE.Color('#0288D1'),  // Outer (dark blue)",
    "// 다층 노이즈 표면 왜곡": "// Multi-layer noise surface distortion",
    "// 프레넬 — 가장자리일수록 시안 글로우": "// Fresnel — tighter cyan glow around the edges",
    "// 맥동": "// Pulsation",
    "// 중심→외곽 그라데이션": "// Center->outer gradient",
    "// 노이즈 표면 패턴": "// Noise surface pattern",
    "// 프레넬 글로우 추가": "// Add Fresnel glow",
    "// 최종 밝기": "// Final brightness",
    "// R3F에 등록": "// Register to R3F",
    "// TypeScript 타입 선언": "// TypeScript type declaration",
    "// 수직 빛줄기 컴포넌트": "// Vertical light ray component",
    "// 메인 항성 컴포넌트 (커스텀 셰이더)": "// Main star component (custom shader)",
    "{/* 광원 1: 시안 메인 */}": "{/* Light Source 1: Cyan Main */}",
    "{/* 광원 2: 흰색 코어 */}": "{/* Light Source 2: White Core */}",
    "{/* 항성 코어 — 커스텀 셰이더 */}": "{/* Star Core — Custom Shader */}",
    "{/* 글로우 레이어 1 — 가까운 후광 */}": "{/* Glow Layer 1 — Near Halo */}",
    "{/* 글로우 레이어 2 — 넓은 후광 */}": "{/* Glow Layer 2 — Wide Halo */}",
    "{/* 글로우 레이어 3 — Bloom이 잡아서 퍼뜨리는 후광 */}": "{/* Glow Layer 3 — Halo spread by Bloom */}",
    "{/* 수직 빛줄기 */}": "{/* Vertical Light Ray */}",
    "{/* 사용자 이름 라벨 */}": "{/* User Name Label */}",
    "const POS_DAMPING    = 0.04;   // 카메라 위치 보간 속도": "const POS_DAMPING    = 0.04;   // Camera position interpolation speed",
    "const LOOKAT_DAMPING = 0.10;   // 시선 보간 (위치보다 빠르게 → 행성이 먼저 시야에 들어옴)": "const LOOKAT_DAMPING = 0.10;   // LookAt interpolation (faster than position -> planet comes into view first)",
    "const THRESHOLD      = 0.3;    // 도착 판정 거리": "const THRESHOLD      = 0.3;    // Arrival distance threshold",
    "// 재사용 벡터 (GC 방지)": "// Reuse vector (prevent GC)",
    "// ── 행성 포커스 ──": "// ── Planet Focus ──",
    "// 매 프레임 행성의 현재 월드 위치 읽기": "// Read current world position of the planet every frame",
    "// 카메라 목표 위치: 행성 기준 바깥쪽 + 위": "// Camera target position: outward + upward relative to the planet",
    "const backDist = radius * 5 + 4;    // 행성 크기에 비례한 거리": "const backDist = radius * 5 + 4;    // Distance proportional to planet size",
    "// 진입 애니메이션: 위치는 부드럽게, 시선은 빠르게": "// Entry animation: soft position, fast line-of-sight",
    "// 애니메이션 완료 후: 행성의 이동분만큼 카메라+타겟을 동일하게 이동 → 지연 0": "// After animation completion: move camera and target identically by the planet's movement amount -> 0 delay",
    "// ── 전체 태양계 뷰 복귀 ──": "// ── Return to Full Solar System View ──",
    "// 보충 문서 Section 4.3 — 태양계 첫 진입 줌인 애니메이션": "// Supplementary Document Section 4.3 — First entry zoom-in animation of the solar system",
    "// (0, 60, 60) → (0, 15, 25), easeOutCubic, ~3초": "// (0, 60, 60) -> (0, 15, 25), easeOutCubic, ~3s",
    "// 시작 전에 카메라를 먼 위치로 초기화": "// Initialize camera to far position before starting",
    "progress.current += delta * 0.33; // 1/3 per sec → ~3초": "progress.current += delta * 0.33; // 1/3 per sec -> ~3s",
    "onPlanetsChange?: (planets: PlanetVisualData[]) => void; // 스토어 동기화 콜백": "onPlanetsChange?: (planets: PlanetVisualData[]) => void; // Store synchronization callback",
    "// changePlanetCount가 호출 직후 스토어 동기화로 인한 initialPlanets 변경을": "// To ignore the initialPlanets change caused by store synchronization immediately after changePlanetCount is called",
    "// 무시하기 위한 보호 플래그": "// Protection flag to ignore",
    "// 외부 데이터 변경 시 동기화 (초기 로드, 프로그레시브 분석 완료)": "// Synchronize upon external data change (initial load, progressive analysis complete)",
    "// 슬라이더 조작 직후에는 skipNextInitialSync로 건너뜀": "// Skip with skipNextInitialSync immediately after slider manipulation",
    "// 행성 수 변경 → 전환 계획 실행": "// Change in planet count -> execute transition plan",
    "// 스토어 동기화 (LeftPanel 등 외부 UI 반영)": "// Sync store (reflect external UI such as LeftPanel)",
    "// 동기화로 인해 initialPlanets effect가 슬롯을 덮어쓰지 않도록 보호": "// Processed to protect against initialPlanets effect overwriting slots due to synchronization",
    "// 이전 exiting 슬롯을 즉시 제거 후 새 계획 적용": "// Discard previous exiting slots immediately and apply new plan",
    "// → 빠른 연속 슬라이더 조작 시 고아 슬롯 누적 방지": "// -> Prevent accumulation of orphan slots during rapid consecutive slider manipulations",
    "// persist — 기존 슬롯 data만 업데이트": "// persist — update existing slot data only",
    "// split — old 슬롯을 exiting + 새 슬롯을 entering": "// split — old slot to exiting + new slot to entering",
    "// merge — old 슬롯들을 exiting + 새 슬롯 entering": "// merge — old slots to exiting + new slot to entering",
    "// appear — 새 슬롯": "// appear — new slot",
    "// disappear — 기존 슬롯을 exiting": "// disappear — existing slot to exiting",
    "// 인덱스 재정렬 (non-exiting만)": "// Reorder indices (non-exiting only)",
    "// exiting 슬롯 제거 콜백": "// Exiting slot removal callback",
    "* Google Takeout \"내 활동\" JSON 포맷 (Gemini 앱)": "* Google Takeout \"My Activity\" JSON format (Gemini App)",
    "* 배열 of activity items": "* Array of activity items",
    "// \"항목을 검색함\" 같은 Google Activity 접미사 제거": "// Target and remove Google Activity suffixes like \"Searched for\"",
    "// 유저 메시지": "// User message",
    "// Gemini 응답 (HTML → 텍스트)": "// Gemini response (HTML -> Text)",
    "// 이름 기반 slug: 카테고리명이 같으면 항상 동일한 ID 보장": "// Name-based slug: ensures the same ID if category names are identical",
    "// ─── 계층적 분류 프롬프트 ───": "// ─── Hierarchical Classification Prompt ───",
    "// ─── 2단계 병합 프롬프트 (500개 초과 시 사용) ───": "// ─── 2-Phase Merge Prompt (Used when exceeding 500) ───",
    "throw new Error('LLM 응답을 JSON으로 파싱할 수 없습니다');": "throw new Error('LLM response cannot be parsed as JSON');",
    "// id, depth 필드를 LLM 응답에 주입": "// Inject id, depth fields into LLM response",
    "// ─── 트리 유틸 ───": "// ─── Tree Utils ───",
    "// ─── 메인 매칭 ───": "// ─── Main Matching ───",
    "// 1. 이름 동일 → persist": "// 1. Name matches -> persist",
    "// 2. old 1개 → new 여러 개 (부모가 자식으로 분열)": "// 2. 1 old -> multiple new (parent splits into children)",
    "// 3. old 여러 개 → new 1개 (자식들이 부모로 합체)": "// 3. multiple old -> 1 new (children merge into parent)",
    "// 4. 매칭 안 된 new → appear": "// 4. Unmatched new -> appear",
    "// 5. 매칭 안 된 old → disappear": "// 5. Unmatched old -> disappear",
    "throw new Error('지원하는 파일을 찾을 수 없습니다');": "throw new Error('Unsupported file format found');",
    "// 행성 색상 팔레트 (블루프린트 Section 5.3)": "// Planet color palette (Blueprint Section 5.3)",
    "'#4FC3F7', // 밝은 파랑": "'#4FC3F7', // Light blue",
    "'#FF7043', // 산호색": "'#FF7043', // Coral",
    "'#66BB6A', // 초록": "'#66BB6A', // Green",
    "'#AB47BC', // 보라": "'#AB47BC', // Purple",
    "'#FFA726', // 주황": "'#FFA726', // Orange",
    "'#EF5350', // 빨강": "'#EF5350', // Red",
    "'#26C6DA', // 시안": "'#26C6DA', // Cyan",
    "'#EC407A', // 핑크": "'#EC407A', // Pink",
    "'#8D6E63', // 갈색": "'#8D6E63', // Brown",
    "'#78909C', // 회청": "'#78909C', // Blue Gray",
    "'#FFEE58', // 노랑": "'#FFEE58', // Yellow",
    "'#5C6BC0', // 인디고": "'#5C6BC0', // Indigo",
    "'#29B6F6', // 하늘": "'#29B6F6', // Sky",
    "'#9CCC65', // 라임": "'#9CCC65', // Lime",
    "'#FF8A65', // 살구": "'#FF8A65', // Apricot"
}

with open('korean_lines.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

for path, matches in data['files'].items():
    with open(path, 'r', encoding='utf-8') as file:
        content = file.read()
    
    # Sort strings by length descending to replace longer strings first and prevent substring interference
    for match in sorted(matches, key=lambda x: len(x['original']), reverse=True):
        orig = match['original']
        # Do not translate regex logic
        if '.replace' in orig:
            continue
        if orig in translations:
            content = content.replace(orig, translations[orig])
    
    with open(path, 'w', encoding='utf-8') as file:
        file.write(content)
print("Replacement completed.")
